// <auto-generated/>
#pragma warning disable
#nullable enable
namespace AHelper.ViewModels
{
    /// <inheritdoc/>
    partial class MainViewModel
    {
        /// <inheritdoc/>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public partial global::AHelper.Models.PerformanceMode SelectedMode
        {
            get => field;
            set
            {
                if (!global::System.Collections.Generic.EqualityComparer<global::AHelper.Models.PerformanceMode>.Default.Equals(field, value))
                {
                    OnSelectedModeChanging(value);
                    OnSelectedModeChanging(default, value);
                    OnPropertyChanging(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangingArgs.SelectedMode);
                    field = value;
                    OnSelectedModeChanged(value);
                    OnSelectedModeChanged(default, value);
                    OnPropertyChanged(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangedArgs.SelectedMode);
                }
            }
        }

        /// <summary>Executes the logic for when <see cref="SelectedMode"/> is changing.</summary>
        /// <param name="value">The new property value being set.</param>
        /// <remarks>This method is invoked right before the value of <see cref="SelectedMode"/> is changed.</remarks>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
        partial void OnSelectedModeChanging(global::AHelper.Models.PerformanceMode value);
        /// <summary>Executes the logic for when <see cref="SelectedMode"/> is changing.</summary>
        /// <param name="oldValue">The previous property value that is being replaced.</param>
        /// <param name="newValue">The new property value being set.</param>
        /// <remarks>This method is invoked right before the value of <see cref="SelectedMode"/> is changed.</remarks>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
        partial void OnSelectedModeChanging(global::AHelper.Models.PerformanceMode oldValue, global::AHelper.Models.PerformanceMode newValue);
        /// <summary>Executes the logic for when <see cref="SelectedMode"/> just changed.</summary>
        /// <param name="value">The new property value that was set.</param>
        /// <remarks>This method is invoked right after the value of <see cref="SelectedMode"/> is changed.</remarks>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
        partial void OnSelectedModeChanged(global::AHelper.Models.PerformanceMode value);
        /// <summary>Executes the logic for when <see cref="SelectedMode"/> just changed.</summary>
        /// <param name="oldValue">The previous property value that was replaced.</param>
        /// <param name="newValue">The new property value that was set.</param>
        /// <remarks>This method is invoked right after the value of <see cref="SelectedMode"/> is changed.</remarks>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
        partial void OnSelectedModeChanged(global::AHelper.Models.PerformanceMode oldValue, global::AHelper.Models.PerformanceMode newValue);
    }
}