// <auto-generated/>
#pragma warning disable
#nullable enable
namespace AHelper.ViewModels
{
    /// <inheritdoc/>
    partial class MainViewModel
    {
        /// <summary>The backing field for <see cref="SelectModeCommand"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.4.0.0")]
        private global::CommunityToolkit.Mvvm.Input.RelayCommand<global::AHelper.Models.PerformanceMode>? selectModeCommand;
        /// <summary>Gets an <see cref="global::CommunityToolkit.Mvvm.Input.IRelayCommand{T}"/> instance wrapping <see cref="SelectMode"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.4.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::CommunityToolkit.Mvvm.Input.IRelayCommand<global::AHelper.Models.PerformanceMode> SelectModeCommand => selectModeCommand ??= new global::CommunityToolkit.Mvvm.Input.RelayCommand<global::AHelper.Models.PerformanceMode>(new global::System.Action<global::AHelper.Models.PerformanceMode>(SelectMode));
    }
}